### ISSUE TITLE
BatchQueue job-collection breaks when batch_token is None

### ISSUE THREAD

**Issue by StephenChan** [beijbom/coralnet#458]
(tl;dr: Rare bug; very disruptive and requires manual recovery; minimal fix should be easy.)

For context, a `BatchJob` model instance is created when there's a new Spacer job to be run through AWS Batch: feature extraction, classifier training, or image classification.

On September 28, from 9:47 AM to 1:07 PM, 36 of the `BatchJob` instances which were created during this period (21 classification, 15 extraction) were left with a `batch_token` of None.

This was problematic for the periodic job-collection task:

```python
def collect_job(self) -> Optional[JobReturnMsg]:
    batch_client = boto3.client(
        ...
    )
    ...

    for job in BatchJob.objects.exclude(status='SUCCEEDED').\
            exclude(status='FAILED'):
        resp = batch_client.describe_jobs(jobs=[job.batch_token])
        ...
```
    
Since when `job.batch_token` was None, the `describe_jobs()` call would crash with an error like this, as seen in the Celery logs:

```
Traceback (most recent call last):
...
  File ".../coralnet/project/vision_backend/queues.py", line 108, in collect_job
    resp = batch_client.describe_jobs(jobs=[job.batch_token])
...
  File ".../site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter jobs[0], value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```
    
And upon crashing, the job-collection task doesn't get the chance to try collecting the rest of the jobs in the queue, even the jobs with valid batch_tokens.

As a result, most classification, extract, and train jobs were blocked up indefinitely. Every few hours, a few jobs would trickle through, since the order of the jobs returned by `BatchJobs.objects...` isn't guaranteed to be always the same. But overall, things were very stuck until I manually marked these 36 jobs as 'failed'.

Google Group thread on the stuck queue: https://groups.google.com/g/coralnet-users/c/7BSazee3jrY

## How batch_token became None

Here's the code that creates the `BatchJob` and later sets the `batch_token`, in `vision_backend/queues.py`:

```python
class BatchQueue(BaseQueue):

    ...

    def submit_job(self, job_msg: JobMsg):

        batch_client = boto3.client(
            ...
        )
        
        ...

        batch_job = BatchJob(job_token=self.get_job_name(job_msg))
        batch_job.save()

        ...

        resp = batch_client.submit_job(
            jobQueue=settings.BATCH_QUEUE,
            jobName=str(batch_job.pk),
            ...
        )
        batch_job.batch_token = resp['jobId']
        batch_job.save()
```

So, the BatchJob is initially created, and then it calls submit_job() on the Boto client, then it sets the batch_token from that Boto call. Basically, if something goes wrong with Boto's submit_job(), then the batch_token ends up as None.

- If Boto's `submit_job()` actually completed, but returned a `resp['jobId']` of None, then I'd expect the submit-job task to finish without errors, and I'd expect the log to include a line saying that the task finished. However, I didn't see such a log line for any of the None batch_token jobs.

- If Boto's `submit_job()` crashed with an error, then I'd expect the log to include a traceback. However, I didn't see such a traceback for any of the None batch_token jobs.

- So I conclude that, for the None batch_token jobs, the task hanged and the process got terminated during the Boto `submit_job()` call.

This is supported by the fact that there were AWS service issues in our region, during the interval that the None batch_token jobs were made (again, September 28, from 9:47 AM to 1:07 PM):

![aws-health-sep-28-detail](https://user-images.githubusercontent.com/857711/196566105-89cc38a6-a236-4c0f-983d-4b2d162bcf3c.png)

![aws-health-sep-28-detail-2](https://user-images.githubusercontent.com/857711/196566126-3f22d234-bf0f-41d1-a560-b8b41c4a7f1e.png)

![aws-health-sep-28-detail-4](https://user-images.githubusercontent.com/857711/196566189-dda55406-713c-4e8b-9729-800ce623f86a.png)

(As seen at: https://health.aws.amazon.com/health/status )

And also, when scrolling through the AWS Batch dashboard, I saw that many CoralNet BatchJob IDs (corresponding to 'Name' in the following screenshots) created during this interval had 0, 2, or even 3 corresponding AWS Batch jobs. They're supposed to be a 1-to-1 correspondence.

![31340xx](https://user-images.githubusercontent.com/857711/196566252-31264b9f-d666-4fd3-99ed-4a01bb03300f.png)

![31341xx](https://user-images.githubusercontent.com/857711/196566260-5e61e3dd-2c32-4d3a-a32e-cc9825b4a0ea.png)

From the CoralNet job-submission code, I see no possible way that we'd create a BatchJob and then call submit_job() for it 2 or 3 times. So I think somewhere in the workings of submit_job(), Boto has some logic which makes it retry the AWS Batch job creation if needed. The fact that it created duplicate jobs probably means the AWS service was struggling.

## What to do about it

In BatchQueue.collect_job(), before passing the batch_token to Batch.Client.describe_jobs(), first check if batch_token is None. If so, then at minimum, mark the job as failed and abort without proceeding to describe_jobs(). Ideally also make sure the job is retried by submitting to AWS Batch again, but the logic for doing so may or may not have to be unique for each job type (feature extract, train, classify).

**Comment by StephenChan** [comment]
There's a wrinkle to this that I missed at first. Again, the code:

```python
class BatchQueue(BaseQueue):

    ...

    def submit_job(self, job_msg: JobMsg):

        batch_client = boto3.client(
            ...
        )
        
        ...

        batch_job = BatchJob(job_token=self.get_job_name(job_msg))
        batch_job.save()

        ...

        resp = batch_client.submit_job(
            jobQueue=settings.BATCH_QUEUE,
            jobName=str(batch_job.pk),
            ...
        )
        batch_job.batch_token = resp['jobId']
        batch_job.save()
```

`batch_job` has already been saved to the database with no `batch_token`, while it's waiting for `batch_client.submit_job()`. While this is happening, `collect_jobs()` runs every 60 seconds, so it's quite possible to collect during the short window when this batch_job has no batch_token, even during normal operation.

To confirm this, I'm currently looking at the past day's worth of celery-worker logs, and there were 8 ParamValidationErrors during this time. Meanwhile, there aren't any no-batch-token BatchJobs to fix. They probably just got unlucky with the timing of batch_client.submit_job() relative to collect_jobs(), and the subsequent run of collect_jobs() had no issues.

So if we immediately clean up the job when a ParamValidationError is detected, that could be a premature cleanup which ends up slowing down some sources. I think the easiest way to address this would be wrapping the above code in a transaction. That way, batch_job won't be visible to other threads (including any threads running collect_job()) while it doesn't have a batch_token yet.
